name: Development
values:
  - key: base_url
    value: 'http://localhost:3000/api'
  - key: auth_token
    value: ''
  - key: task_id
    value: ''
  - key: seed_user_email
    value: ada@example.com
  - key: seed_user_password
    value: password123
  - key: seed_other_user_email
    value: grace@example.com
  - key: seed_admin_email
    value: admin@example.com
  - key: seed_admin_password
    value: adminpass123
