name: Production
values:
  - key: base_url
    value: 'http://localhost:3002/api'
    type: default
    enabled: true
  - key: auth_token
    value: ''
    type: secret
    enabled: true
  - key: task_id
    value: ''
    type: default
    enabled: true
  - key: seed_user_email
    value: 'ada@example.com'
    type: default
    enabled: true
  - key: seed_user_password
    value: 'password123'
    type: secret
    enabled: true
  - key: seed_other_user_email
    value: 'grace@example.com'
    type: default
    enabled: true
  - key: seed_admin_email
    value: 'admin@example.com'
    type: default
    enabled: true
  - key: seed_admin_password
    value: 'adminpass123'
    type: secret
    enabled: true
